from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os
from datetime import datetime

# Use SQLite for local dev, Postgres for Prod (Railway)
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./alphapulse.db")

engine = create_engine(
    DATABASE_URL, connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

class Signal(Base):
    """
    Stores every 'Pro' signal generated by the AI for historical verification.
    """
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    signal_type = Column(String) # LONG / SHORT
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    confidence = Column(Float)
    
    # Outcome tracking (To be updated later by a checker job)
    outcome = Column(String, default="PENDING") # PENDING, WIN, LOSS
    pnl_percent = Column(Float, default=0.0)

class PerformanceSnapshot(Base):
    """
    Daily snapshot of system performance.
    """
    __tablename__ = "performance"
    
    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, default=datetime.utcnow)
    total_signals = Column(Integer)
    win_rate = Column(Float) # e.g. 78.5
    cumulative_pnl = Column(Float) # e.g. 1450.0 (%)

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
